/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iteye_weimingtom_mrubyjni_MRubyJNI */

#ifndef _Included_com_iteye_weimingtom_mrubyjni_MRubyJNI
#define _Included_com_iteye_weimingtom_mrubyjni_MRubyJNI
#ifdef __cplusplus
extern "C" {
#endif
#undef com_iteye_weimingtom_mrubyjni_MRubyJNI_D
#define com_iteye_weimingtom_mrubyjni_MRubyJNI_D 1L
/*
 * Class:     com_iteye_weimingtom_mrubyjni_MRubyJNI
 * Method:    exec
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_iteye_weimingtom_mrubyjni_MRubyJNI_exec
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
