/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iteye_weimingtom_jni_study_Test */

#ifndef _Included_com_iteye_weimingtom_jni_study_Test
#define _Included_com_iteye_weimingtom_jni_study_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iteye_weimingtom_jni_study_Test
 * Method:    mycall
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_iteye_weimingtom_jni_study_Test_mycall
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
