/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iteye_weimingtom_jni_study_Test2 */

#ifndef _Included_com_iteye_weimingtom_jni_study_Test2
#define _Included_com_iteye_weimingtom_jni_study_Test2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iteye_weimingtom_jni_study_Test2
 * Method:    mycall
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_iteye_weimingtom_jni_study_Test2_mycall
  (JNIEnv *, jobject);

/*
 * Class:     com_iteye_weimingtom_jni_study_Test2
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_iteye_weimingtom_jni_study_Test2_print
  (JNIEnv *, jobject);

/*
 * Class:     com_iteye_weimingtom_jni_study_Test2
 * Method:    sumArray
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_iteye_weimingtom_jni_study_Test2_sumArray
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_iteye_weimingtom_jni_study_Test2
 * Method:    initInt2DArray
 * Signature: (I)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_com_iteye_weimingtom_jni_study_Test2_initInt2DArray
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_iteye_weimingtom_jni_study_Test2
 * Method:    getLine
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_iteye_weimingtom_jni_study_Test2_getLine
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_iteye_weimingtom_jni_study_Test2
 * Method:    getLine2
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_iteye_weimingtom_jni_study_Test2_getLine2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_iteye_weimingtom_jni_study_Test2
 * Method:    accessField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_iteye_weimingtom_jni_study_Test2_accessField
  (JNIEnv *, jobject);

/*
 * Class:     com_iteye_weimingtom_jni_study_Test2
 * Method:    accessField2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_iteye_weimingtom_jni_study_Test2_accessField2
  (JNIEnv *, jobject);

/*
 * Class:     com_iteye_weimingtom_jni_study_Test2
 * Method:    nativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_iteye_weimingtom_jni_study_Test2_nativeMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_iteye_weimingtom_jni_study_Test2
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_iteye_weimingtom_jni_study_Test2_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     com_iteye_weimingtom_jni_study_Test2
 * Method:    nativeMethod2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_iteye_weimingtom_jni_study_Test2_nativeMethod2
  (JNIEnv *, jobject);

/*
 * Class:     com_iteye_weimingtom_jni_study_Test2
 * Method:    nativeMethod3
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_iteye_weimingtom_jni_study_Test2_nativeMethod3
  (JNIEnv *, jclass);

/*
 * Class:     com_iteye_weimingtom_jni_study_Test2
 * Method:    nativeMethod4
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_iteye_weimingtom_jni_study_Test2_nativeMethod4
  (JNIEnv *, jclass);

/*
 * Class:     com_iteye_weimingtom_jni_study_Test2
 * Method:    accessField5
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_iteye_weimingtom_jni_study_Test2_accessField5
  (JNIEnv *, jobject);

/*
 * Class:     com_iteye_weimingtom_jni_study_Test2
 * Method:    nativeMethod6
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_iteye_weimingtom_jni_study_Test2_nativeMethod6
  (JNIEnv *, jobject);

/*
 * Class:     com_iteye_weimingtom_jni_study_Test2
 * Method:    nativeMethod7
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_iteye_weimingtom_jni_study_Test2_nativeMethod7
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
