/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iteye_weimingtom_rubyjni_RubyJNI */

#ifndef _Included_com_iteye_weimingtom_rubyjni_RubyJNI
#define _Included_com_iteye_weimingtom_rubyjni_RubyJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iteye_weimingtom_rubyjni_RubyJNI
 * Method:    exec
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_iteye_weimingtom_rubyjni_RubyJNI_exec
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
